language: c

sudo: required

#addons:
#  apt:
#    packages:
#    - lua5.1
#    - liblua5.1-filesystem0
#    - luarocks
#    - lua-penlight
#    - p7zip-full
#    - python-sphinx

install:
- sudo apt-get update
- sudo apt-get install lua5.1 liblua5.1-filesystem0 luarocks p7zip-full python-sphinx
- sudo luarocks install penlight

script:
- lua generate.lua -r
- ls -la output/
- lua precommit.lua
- ls -la doc/_build/html/

notifications:
  email:
    on_failure: always
    on_success: change

env:
  secure: DGBC1v2vTB5KdF1x5pC1HPeEUGRkKIlDlLwotm4Tlk6sb1ypuz7C4GLtkX8kPjEeQW9QEfbCWbkW1J2VQ4DBolZPnUWPCRUYG/l+HmlxvRhVdFHcUDiN4lfuqxCBRplRreUuklDoSRTt1iyrFMQkLsndQXA6A9GR2Y9qd3qAQFA=
