language: c
sudo: required
install:
- sudo apt-get update
- sudo apt-get install lua5.1 luarocks p7zip-full python-sphinx
- sudo luarocks install penlight
script:
- bash travis.sh
notifications:
  email:
    on_failure: always
    on_success: change
env:
  global:
  - GH_REF: github.com/keneanung/svof.git
  - GH_USER: keneanung
  - secure: V0HawetWvekNYeatM50TFRbAH00QadMCA7urzX3ts2eFsrrA8nKPzayezqQJ0BUVXOuSzbo4IY0bv2VM9lSO7/e+3ytv4ZTOYaJTm4dySSYwOyB6fHafuQv2FMJ+yUBPN07zCkIJ81wUf5VZCeBzOFpLz+kypu7lqsVgHyiMxQpRkL9MUFHwtaBpgqusnenkltflU18n8KE13r55OEvuPoc8GR2JimHgDsJbyVP/FwWRcrYM9AoINo1F4FAnU/bN/oXXfULNIAW27WkyyfWitH1HByWWpZpescxotQmd2R+YuIdcU3V7xkdfWLHvFpK9hpAhkQgFCZXNzjrQyfEJ9kh6fuVc6gCNhTpOgFZ1wk7a6AAi3BNs7I8Ne/hqZ7G+onMkzZVyVQAfzI0SSFYin07T5MhxvYNiCND9kiy+eYD8vQZVvsOj7sORi37Ip/ODRj6HdtwyJLOxdZMAviFFBTr1L10Vg1nfUZv2R7vh+UD7YmEkbb0NJuaXDzdJmMpvHbUokh29XBjDXXezXzAxEYtjFHRQTrMSkARi6F0fpek9PZ+Mz/RzdVy63bcigz2jgISV6Ea9TgIdOU4XjzickJUzGiGUU/OooFTh1KTLy7ZQ1wuziH+WWsvo7qQu2siitXJ5Ec0QQn44YIjVgqF1pVRMbg0T8scFsqXkCQ8oqoc=
