language: c

sudo: false

addons:
  apt:
    packages:
    - lua5.1
    - lua-filesystem
    - luarocks
    - lua-penlight
    - p7zip-full
    - python-sphinx

script:
- lua generate.lua -r
- lua precommit.lua

notifications:
  email:
    on_failure: always
    on_success: change

env:
  secure: DGBC1v2vTB5KdF1x5pC1HPeEUGRkKIlDlLwotm4Tlk6sb1ypuz7C4GLtkX8kPjEeQW9QEfbCWbkW1J2VQ4DBolZPnUWPCRUYG/l+HmlxvRhVdFHcUDiN4lfuqxCBRplRreUuklDoSRTt1iyrFMQkLsndQXA6A9GR2Y9qd3qAQFA=
